/********************************************************************
* /global/project/projectdirs/captain/users/pmadigan/pds_analysis/pds_analysisCode/PDSAnalysis_cc_ACLiC_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /global/project/projectdirs/captain/users/pmadigan/pds_analysis/pds_analysisCode/PDSAnalysis_cc_ACLiC_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablePDSAnalysis_cc_ACLiC_dict();
extern void G__cpp_setup_inheritancePDSAnalysis_cc_ACLiC_dict();
extern void G__cpp_setup_typetablePDSAnalysis_cc_ACLiC_dict();
extern void G__cpp_setup_memvarPDSAnalysis_cc_ACLiC_dict();
extern void G__cpp_setup_globalPDSAnalysis_cc_ACLiC_dict();
extern void G__cpp_setup_memfuncPDSAnalysis_cc_ACLiC_dict();
extern void G__cpp_setup_funcPDSAnalysis_cc_ACLiC_dict();
extern void G__set_cpp_environmentPDSAnalysis_cc_ACLiC_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/global/project/projectdirs/captain/users/pmadigan/pds_analysis/pds_analysisCode/./PDSAnalysis.cc"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__PDSAnalysis_cc_ACLiC_dictLN_complexlEdoublegR;
extern G__linked_taginfo G__PDSAnalysis_cc_ACLiC_dictLN_TString;
extern G__linked_taginfo G__PDSAnalysis_cc_ACLiC_dictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__PDSAnalysis_cc_ACLiC_dictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__PDSAnalysis_cc_ACLiC_dictLN_TH1F;
extern G__linked_taginfo G__PDSAnalysis_cc_ACLiC_dictLN_TTree;
extern G__linked_taginfo G__PDSAnalysis_cc_ACLiC_dictLN_TCanvas;
extern G__linked_taginfo G__PDSAnalysis_cc_ACLiC_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__PDSAnalysis_cc_ACLiC_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__PDSAnalysis_cc_ACLiC_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PDSAnalysis_cc_ACLiC_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__PDSAnalysis_cc_ACLiC_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PDSAnalysis_cc_ACLiC_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__PDSAnalysis_cc_ACLiC_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__PDSAnalysis_cc_ACLiC_dictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__PDSAnalysis_cc_ACLiC_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__PDSAnalysis_cc_ACLiC_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PDSAnalysis_cc_ACLiC_dictLN_valarraylEcomplexlEdoublegRsPgR;
extern G__linked_taginfo G__PDSAnalysis_cc_ACLiC_dictLN_PDSAnalysis;
extern G__linked_taginfo G__PDSAnalysis_cc_ACLiC_dictLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR;
extern G__linked_taginfo G__PDSAnalysis_cc_ACLiC_dictLN_reverse_iteratorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PDSAnalysis_cc_ACLiC_dictLN_vectorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcOallocatorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRsPgRsPgR;
extern G__linked_taginfo G__PDSAnalysis_cc_ACLiC_dictLN_reverse_iteratorlEvectorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcOallocatorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PDSAnalysis_cc_ACLiC_dictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__PDSAnalysis_cc_ACLiC_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
