/********************************************************************
* /global/project/projectdirs/captain/users/pmadigan/pds_analysis/pds_analysisCode/./macros/nitrogen_C_ACLiC_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /global/project/projectdirs/captain/users/pmadigan/pds_analysis/pds_analysisCode/./macros/nitrogen_C_ACLiC_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablenitrogen_C_ACLiC_dict();
extern void G__cpp_setup_inheritancenitrogen_C_ACLiC_dict();
extern void G__cpp_setup_typetablenitrogen_C_ACLiC_dict();
extern void G__cpp_setup_memvarnitrogen_C_ACLiC_dict();
extern void G__cpp_setup_globalnitrogen_C_ACLiC_dict();
extern void G__cpp_setup_memfuncnitrogen_C_ACLiC_dict();
extern void G__cpp_setup_funcnitrogen_C_ACLiC_dict();
extern void G__set_cpp_environmentnitrogen_C_ACLiC_dict();
}


#include "/tmp/rootcint_EncXBx.h"
